services:
  app:
    build:
      context: .
      dockerfile: Containerfile
      args:
        GIT_REVISION: ${GIT_REVISION}
    image: ${IMAGE_NAME}:latest

    # Working directory inside the container
    working_dir: /app

    # Volume mounts
    volumes:
      - data_volume:/app/data
      - deno_dir:/deno-dir

    # Port mappings (host:container)
    ports:
      - "${EXTERNAL_PORT}:8000"

    # Environment variables
    environment:
      - ORW_PUBLIC_URL=${ORW_PUBLIC_URL:-http://localhost:8000}
      - ORW_REPOSITORY_URL=${ORW_REPOSITORY_URL:-}
      - ORW_STORAGE_PUBLIC_URL
      - ORW_BUILD_STRING
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=8000

## always set 'external: true' and give the volume a static name, to NOT let *-compose handle volumes
## otherwise the volume name gets drived from the parent directory name etc
## if you suddenly get greeted by an empty DB, you now know why
volumes:
  data_volume:
    external: true
    name: "${VOLUME_NAME}"
  deno_dir:
    external: true
    name: "deno_dir"
